//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerServices
    {
        public int PartnerServiceID { get; set; }
        public int ServiceID { get; set; }
        public int PartnerID { get; set; }
        public int Количество_услуг { get; set; }
        public System.DateTime Дата_выполнения { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Services Services { get; set; }
    }
}
