//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.PartnerServices = new HashSet<PartnerServices>();
        }
    
        public int ServiceID { get; set; }
        public int ServiceTypeID { get; set; }
        public string Наименование_услуги { get; set; }
        public string Код_услуги { get; set; }
        public decimal Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerServices> PartnerServices { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
