//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int IdUser { get; set; }
        public int IdRole { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
